# Generated by Django 4.2.4 on 2023-08-29 20:09

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
    ]
