version: "3"

networks:
    app-tier-tms:
        driver: bridge
    external_network:
        external: true

services:
    tms_web:
        container_name: tms_web
        restart: always
        user: "0:0"
        build:
            context: .
            dockerfile: Dockerfile
        command: ./deployment/start-app
        networks:
            - external_network
            - app-tier-tms
        env_file:
            - .env
        ports:
            - "127.0.0.1:8001:8000"
