#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

postgres_ready() {
  python <<END
import sys
import psycopg2

try:
    pgdb = psycopg2.connect(
        host='${PROD_DB_HOST}',
        user='${PROD_DB_USER}',
        password='${PROD_DB_PASS}',
        port='${PROD_DB_PORT}'
    )
except psycopg2.OperationalError:
    print('Break in DB connection on deployment')
    sys.exit(-1)
sys.exit(0)
END
}
until postgres_ready; do
  echo >&2 'Waiting for PostgreSQL to become available...'
  sleep 1
done
echo >&2 'PostgreSQL is available'

exec "$@"
