#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

# Collect static files
echo "Collect static files"
python manage.py collectstatic --noinput

# Apply database migrations
echo "Apply database migrations"
python manage.py migrate --noinput

#Remove unused permissions and contenttypes
python manage.py remove_stale_contenttypes --include-stale-apps --no-input

# Start server
echo "Starting server"

#python manage.py runserver 0.0.0.0:8000
hypercorn core.wsgi:application --bind 0.0.0.0:8000
