name: Check Code Quality

on:
    pull_requests:
        branches:
            - master

jobs:
    build:
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 flake8-bandit flake8-bugbear flake8-django flake8-spellcheck 
                  pip install flake8 annotations flake8 quotes flake8-comprehensions flake8-string-format
                  pip install flake8-debugger flake8-eradicate flake8-functions-names pep8-naming
            - name: Check Code Quality
              run: |
                  pip install flake8
                  flake8 .
